bstVector-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 bst-vector.c ../ADTs/bst.c ../ADTs/bst.h ../Util/util.c ../Util/util.h -o bst-vector
bstVector-run:
	./bst-vector
avl-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 avl.c ../ADTs/avl.c ../ADTs/avl.h ../Util/util.c ../Util/util.h -o avl
avl-run:
	./avl
avlBst-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 avl-bst.c ../ADTs/bst.c ../ADTs/bst.h ../ADTs/avl.c ../ADTs/avl.h ../Util/util.c ../Util/util.h -o avl-bst
avlBst-run:
	./avl-bst
treeInsertion-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 tree-insertion.c ../ADTs/avl.c ../ADTs/avl.h ../ADTs/bst.c ../ADTs/bst.h ../Util/util.c ../Util/util.h -o tree-insertion
treeInsertion-run:
	./tree-insertion
popAvlIntersection-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 pop-avl-intersection.c ../ADTs/avl.c ../ADTs/avl.h ../ADTs/bst.c ../ADTs/bst.h ../Util/util.c ../Util/util.h -o pop-avl-intersection
popAvlIntersection-run:
	./pop-avl-intersection
mergeTest-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 merge-sort.c ../ADTs/avl.c ../ADTs/avl.h ../ADTs/bst.c ../ADTs/bst.h ../Util/util.c ../Util/util.h -o merge-sort
mergeTest-run:
	./merge-sort
bstRemoving-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 bst-removing.c ../ADTs/avl.c ../ADTs/avl.h ../ADTs/bst.c ../ADTs/bst.h ../Util/util.c ../Util/util.h -o bst-removing
bstRemoving-run:
	./bst-removing
main1Test-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 main1-test.c ../ADTs/avl.c ../ADTs/avl.h ../ADTs/bst.c ../ADTs/bst.h ../Util/util.c ../Util/util.h -o main1-test
main1Test-run:
	./main1-test