bstVector-main:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=c99 bst-vector.c ../ADTs/bst.c ../ADTs/bst.h ../Util/util.c ../Util/util.h -o bst-vector
bstVector-run:
	./bst-vector